// Code generated by Slice Machine. DO NOT EDIT.

import FirstSlice from './FirstSlice';
import TituloPrincipal from './TituloPrincipal';

export {
	FirstSlice,
	TituloPrincipal,
};

export const components = {
	first_slice: FirstSlice,
	titulo_principal: TituloPrincipal,
};
